disabled_rules:
  - file_length
  - trailing_whitespace
  - identifier_name
  - type_body_length
  - function_body_length
  - type_name
  - todo
  - redundant_optional_initialization
  - cyclomatic_complexity
  - force_try

line_length: 100
