on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

name: Run test suite

jobs:
  run-tests:
    # macos runners and their supported xcode/ios versions can be found here:
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
    runs-on: macos-12
    strategy:
      matrix:
        include:
          - xcode: "14.2"
            ios:   "16.2"
    
    name: Test iOS ${{ matrix.ios }}
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: ./scripts/run_tests.sh "iOS Simulator" "iPhone 14 Pro" "${{ matrix.ios }}" "${{ matrix.xcode }}" | xcpretty && exit ${PIPESTATUS[0]}
