on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

name: Run test suite

jobs:
  run-tests:
    # macos runners and their supported xcode/ios versions can be found here:
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
    runs-on: macos-12
    strategy:
      matrix:
        include:
          - xcode: "14.2"
            ios:   "16.2"

    name: Test iOS ${{ matrix.ios }}
    steps:
      - uses: actions/checkout@v2

      - name: Cache packages
        id: cache-swiftpm
        uses: actions/cache@v3
        env:
          cache-name: cache-swift-pm
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/Library/Caches/org.swift.swiftpm/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cache Xcode build artifacts
        id: cache-build
        uses: actions/cache@v3
        env:
          cache-name: cache-build
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-xcode-

      - run:
        name: Set IgnoreFileSystemDeviceInodeChanges flag
        command: defaults write com.apple.dt.XCBuild IgnoreFileSystemDeviceInodeChanges -bool YES

      - name: Run unit tests
        run: ./scripts/run_tests.sh "iOS Simulator" "iPhone 14 Pro" "${{ matrix.ios }}" "${{ matrix.xcode }}" | xcpretty && exit ${PIPESTATUS[0]}
