on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

name: SwiftLint

jobs:
  SwiftLint:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
            set-safe-directory: '/github/workspace'
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@master
        env:
          DIFF_BASE: ${{ github.base_ref }}